### ISSUE TITLE
shoelace_kitchensink example scrolling bug on IOS Desktop.

### ISSUE THREAD

**Issue by gedw99** [delaneyj/datastar#22]
https://data-star.dev/examples/shoelace_kitchensink is broken in Safari ( Desktop ), but not on IOS ( mobile ). 

The bug is that when you scroll, the text and combo box stay fixed, but everything else scrolls correctly.

<img width="1728" alt="Screenshot 2024-04-21 at 11 32 37" src="https://github.com/delaneyj/datastar/assets/53147028/01dcf4a8-e5ea-493d-b322-f695c1fe2758">

**Comment by delaneyj** [comment]
Nothing about Datastar should effect rendering, it's most likely shoelace issue.

**Comment by gedw99** [comment]
local it work son desktop, so I think this has been fixed ....
