### ISSUE TITLE
client sync

### ISSUE THREAD

**Issue by gedw99** [delaneyj/datastar#25]
Was wondering if we want to have a mechanism to update clients that happen to be looking at the same page URL ?  

The idea is that one user is changing some aspect, and when they change it, we want the other users to also see that change.

This is where NATS is pretty cool.

A few examples of where this "pattern" would be useful :

https://data-star.dev/examples/value_select where the models list was changes by 1 user, and other users can then see it change in their drop downs.

https://data-star.dev/examples/infinite_scroll which is read only, but if one of the rows changed ( due to some other user doing a mutation of the underlying data ), all other users would see it.

## Why ?

Well one reason is that you get way less Transactions that fail validation rules back in your storage layer.

The other one is for Dashboards where you want real time sync.

**Comment by delaneyj** [comment]
I'll be working on a game server that shows this exact behavior between NATS and Datastar

**Comment by gedw99** [comment]
oh great. I really hope that some of the NATS aspects get shown in the Datastar repo as examples, because I think it will help me and others.


I started using Corrosion as my DB with NATS now.  It's a CRDT Sqlite DB in Rust with an elegant HTTP API.  SO then its very easy to do a "select * ..." as a subscription and just feed it up to NATS and SSE with Datastar

https://github.com/superfly/corrosion

https://superfly.github.io/corrosion/api/subscriptions.html shows how easy it is.

The DB will scale out master master with nothing needed, thanks to the CRDT. It's working well for me.

I am going to write a golang API to consume easily off it and manage the subscription data to make it more robust.

**Comment by gedw99** [comment]
> I'll be working on a game server that shows this exact behavior between NATS and Datastar

Would be good if we had a basic example in this repo. Maybe chat ..

I agree that nats is the way to do it .

**Comment by delaneyj** [comment]
So I've been trying to think of a way to show this off without a lot of code.. Right now my plan for the front page is to replace the demo with a gameboy emulator that has a shared state of a game like pokemon.  Everyone is playing with the same controller.  I know twitch did this over 10 years ago but it would be trivial with NATS+Datastar

**Comment by gedw99** [comment]
I don’t know that old demo you are referring too.

I just wanted a simple todo or similar, where all browser tabs are in sync , without hitting refresh.

Very very simple and easy to learn from .

**Comment by delaneyj** [comment]
My only concern with chat or a to-do is is very easy to get buried with bad content, then you have to deal with considering it's spam detection type stuff, I guess I can do it and if it becomes a problem we can try something else

**Comment by delaneyj** [comment]
I don't know much about turnstile @nickchomey but I'll take a look!

**Comment by gedw99** [comment]
> My only concern with chat or a to-do is is very easy to get buried with bad content, then you have to deal with considering it's spam detection type stuff, I guess I can do it and if it becomes a problem we can try something else

Yeah you're right in that bad actors will put up improper content into a chat. If it does become a problem, we can add a 10 minute timer that wipes all the data.

**Comment by delaneyj** [comment]
This has been covered by #74
