### ISSUE TITLE
dependencies setup to be cross platform

### ISSUE THREAD

**Issue by gedw99** [delaneyj/datastar#4]
Any thoughts of best way to make it easy to setup for cross platform

task is fine but I think we could easily add a reps command that installs

https://github.com/itchyny/gojq

#go install github.com/itchyny/gojq/cmd/gojq@latest
go install github.com/itchyny/gojq/cmd/gojq@v0.12.14

then Task file works for me with just changing "jq" to "gojq"
```sh
VERSION:
    sh: cat library/package.json| gojq -r .version
```

--

for wget, we can replace with go-getter I think. 
https://github.com/hashicorp/go-getter

**Comment by gedw99** [comment]
cool. I will do it.

One thing that blocks me atm in Task compared to Makefile is doing "if else" checks when I check the "OS" and "ARCH", and then either call brew install or whatever windows and linux want.

Maybe you have an idea for how to do this in a Taskfile OR we just change to using  a Makefile.

This is a Makefile that does it using the golang to detect OS and ARCH. SO it assumes golang is installed which is a given...

```sh

OS_GO_BIN_NAME=go
ifeq ($(shell uname),Windows)
	OS_GO_BIN_NAME=go.exe
endif
OS_GO_OS=$(shell $(OS_GO_BIN_NAME) env GOOS)
OS_GO_VERSION=$(shell $(OS_GO_BIN_NAME) env GOVERSION)
OS_GO_ARCH=$(shell $(OS_GO_BIN_NAME) env GOARCH)

dep-tools:
	@echo ""
	@echo "Dep tools phase ..."

ifeq ($(OS_GO_OS),windows)
	@echo ""
	@echo "Detected Windows ..."
	
	@echo ""
endif

ifeq ($(OS_GO_OS),darwin)
	@echo ""
	@echo "Detected Darwin ..."

	@echo ""
	@echo "Installing create-dmg with brew, so that we can do packaging on Mac."
	@echo ""
	brew install create-dmg
	@echo ""
endif

ifeq ($(OS_GO_OS),linux)
	@echo ""
	@echo "Detected Linux ..."
	@echo ""
	@echo "Installing various things, so that we can build and run on Linux."
	@echo ""
	sudo apt install gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev libfuse2

	@echo ""
	@echo "Installing pkg2appimage with wget, so that we can do packaging with appimage on Linux."
	@echo ""
	wget -c $(shell wget -q https://api.github.com/repos/AppImageCommunity/pkg2appimage/releases -O - | grep "pkg2appimage-.*-x86_64.AppImage" | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
	chmod +x ./pkg2appimage-*.AppImage
	mkdir -p dist
	mv ./pkg2appimage-*.AppImage ./dist/

	@echo ""
endif
```

**Comment by delaneyj** [comment]
I think you are looking for https://taskfile.dev/usage/#os-specific-taskfiles

**Comment by gedw99** [comment]
https://github.com/delaneyj/datastar/compare/main...gedw99:datastar:main

dont need any per OS stuff. See the tool.mk.

Taskfile_tool.yaml is the one that will do what tool.mk does currently.  Still working it out though because Task can't evaluate all the variables before it runs, which make file can do. So might have to turn things into more function calls for the Task file. Just guessing as I only have 5 minutes experience with task :)

Let me know if you have any clues

**Comment by gedw99** [comment]
Got stuck here: https://github.com/go-task/task/discussions/1429

**Comment by delaneyj** [comment]
Guess I'm a little confused this is just related to deploying the docs to `fly.io`, why would you need to do this at all?

**Comment by gedw99** [comment]
Its cool . I wanted to make it cross platform.

I ended up just wrapping Task with Make and it works on windows , Mac and Linux fine now. Just to get it working . 

If you want we can revisit this later to move everything to task later .

Will close for now ..
