### ISSUE TITLE
flashing in many gui examples. v0.13.1 caused a regression.

### ISSUE THREAD

**Issue by gedw99** [delaneyj/datastar#46]
https://github.com/delaneyj/datastar/releases/tag/v0.13.1 is broken with flashing in GUI 
https://github.com/delaneyj/datastar/releases/tag/v0.13.0 works

http://localhost:8080/examples/click_to_edit shows what I mean by "flashing"..

**Comment by delaneyj** [comment]
Thanks @gedw99 for the report, we didn't run the test suite prior to the hot fix.  This PR passes, sorry about that.  We need to work on a set of Github Actions that auto run prior to accepting PRs in the future

**Comment by gedw99** [comment]
Nice work in the test suite btw!!

**Comment by delaneyj** [comment]
@rphumulock is to thank!
