### ISSUE TITLE
WASM in browser too 

### ISSUE THREAD

**Issue by gedw99** [delaneyj/datastar#49]
I saw a golang htmx project that used the same code on front end and back end.

If there is interest let me know ..

My intent with the issue is to raise the idea of caching html in a Service worker .

**Comment by delaneyj** [comment]
Sure would be happy to have as many examples as possible!

**Comment by delaneyj** [comment]
I guess i'm not seeing what this gives you versus having a cache in localStorage

**Comment by gedw99** [comment]
True point. A cache in a service worker is the low hanging fruit.

I also question the value of the WASM.

**Comment by delaneyj** [comment]
I've been thinking about actually moving datastar plugins to wasm for 2.0 but that's a ways out

**Comment by gedw99** [comment]
I assume thats using wazero and running on the server ?

**Comment by delaneyj** [comment]
no Datastar is :100: in the browser, basically running a extism host with codegen rpc interface for each plugin

**Comment by gedw99** [comment]
Yeah I know extism.

your treasing :) sounds like an interesting thing whatever your up to :)

**Comment by delaneyj** [comment]
I'm closing this for now as there is nothing actionable to do for now.
