### ISSUE TITLE
reactive DB

### ISSUE THREAD

**Issue by gedw99** [delaneyj/datastar#5]
Hey @delaneyj 

The ECS system looks really cool man in Geck !!

I have been using these sorts of setups with SurrealDB and NATS. Surreal is fully reactive like nats. You know the drill...

https://github.com/Odonno/ultime is a full stack example.

https://github.com/Odonno/surrealdb-migrations is where the real time data migration happens. 

Surreal is quite something that I have been using for a while and it's like nothing else out there because the data is a graph. It can scale out with a KV store ( maybe nats :) )

**Comment by delaneyj** [comment]
Yeah I want to make fully serializable, including deltas. It's actually very similar to what they're trying to do but in pure go

**Comment by gedw99** [comment]
Deltas - yes please !!

**Comment by delaneyj** [comment]
Wrong repo for G.E.C.K. (but a new way faster version is available using code gen).  Closing for now
