### ISSUE TITLE
Functions as a WASM 

### ISSUE THREAD

**Issue by gedw99** [delaneyj/datastar#7]
Looks like it’s possible to make each example page a WASM . So we could do serverless style serving of each as a WASM.

not looked into how I can do it with data-star fully.

I have his htmx demo where the same WASM on the server is loaded into the browser as a service worker . 

So first request hits the server fully but the response embeds an asynchronous loading script to load the same WASM into the browser as a service worker.

the next client request then hits the service worker . That worker knows it’s in the client and calls for data ( if not cached ).

If you’re interested I can send you the demo.

**Comment by delaneyj** [comment]
Nothing actionable that I can see for now.  Feel free to reopen
