### ISSUE TITLE
Demo site on mobile is a desktop gui

### ISSUE THREAD

**Issue by gedw99** [delaneyj/datastar#80]
Needs some attention as anyone hitting it on a mobile gets a terrible experience .

big turn off

**Comment by delaneyj** [comment]
PRs welcome

**Comment by gedw99** [comment]
Totally ...

Will try to give it a go.

**Comment by delaneyj** [comment]
I might have a fix in flight, if it's still a problem in v0.16 will have to try a different path.  I thought i had this all worked out

**Comment by gedw99** [comment]
ok will hold off . Thanks for the heads up.

**Comment by delaneyj** [comment]
Try the front page now, if it works close issue please.

**Comment by gedw99** [comment]
I tried it. 

It’s better.

On my iPhone max , the font and spacing is way too small …
![DATASTAR jpeg](https://github.com/delaneyj/datastar/assets/53147028/fcf1b2ce-0dd3-43ba-8807-9cf244babc31)

**Comment by delaneyj** [comment]
I pushed an update to the tailwind typography baseline.  I'll close for now, its hard to test without an IPhone, feel free to PR an update to the Daisy/TW classes if you continue to have issues

**Comment by gedw99** [comment]
If your on MAC Safari can simulate an iPhone , etc .

**Comment by delaneyj** [comment]
Don't have any Apple products of any kind

**Comment by gedw99** [comment]
> Don't have any Apple products of any kind

I tested it for free here... Users a real iPhone with Safari.

https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=www.browserstack.com%2Fwelcome&speed=1

<img width="1728" alt="Screenshot 2024-06-19 at 18 47 47" src="https://github.com/delaneyj/datastar/assets/53147028/9e47ab36-66df-44da-ba41-18501e78105b">

**Comment by delaneyj** [comment]
Learned about the details of https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag, hopefully its better now
