### ISSUE TITLE
scroll refresh bug on sync

### ISSUE THREAD

**Issue by gedw99** [delaneyj/datastar#87]
Tested  Mac Safari,  iPhone Safari. Mac Chrome and got same behaviour.

go to main page at https://data-star.dev, then to bottom and click "Lets Gets started", then hit back.

1. It does not go back to the same scroll position. 
2. If you scroll up and down the whole page you will notice it gets stuck on the TODO sync area.

Hopefully I have described this well enough. 

BTW having the state reset button in the TODO example helps for isolating bugs because I can take things back to a base state.

**Comment by delaneyj** [comment]
Should work now

**Comment by gedw99** [comment]
Nice one .will wait until next tagged release to cross browser test

**Comment by gedw99** [comment]
Fixed on iOS Safari. Can close I think.

It no longer defaults to navigating to the todo section.

There is a a jarring FOUC aspect that I will raise in another issue.
