### ISSUE TITLE
Sync activation bug on first time user goes to https://data-star.dev

### ISSUE THREAD

**Issue by gedw99** [delaneyj/datastar#88]
Tested on Mac Safari, iPhone Safari and Mac Chrome

The first time a user goes to https://data-star.dev, there is about a 10 to 15 seconds delay until clicks on todo checkboxes actually activates.

If you close and open the tab again, you will not experience this delay.

**Comment by delaneyj** [comment]
Can't reproduce

**Comment by gedw99** [comment]
I will try to war out the sequence to reproduce. Me and 2 others had it.

**Comment by gedw99** [comment]
Ok I worked out how to Reproduce:

From https://data-star.dev:

In Mac Safari I clear Local storage and Session Storage, and then refresh the page in the browser, and the bug occurs.

I also tried it in Chrome, but got it happening in a non deterministic way.   

Will try to work it out a bit more when I get a chance but thats how far I got so far..

**Comment by delaneyj** [comment]
Think same issues as #91
