### ISSUE TITLE
add version to page header or footer so that Issues raised are scopes to the version the user tested on

### ISSUE THREAD

**Issue by gedw99** [delaneyj/datastar#89]
Just think it will make it easier for bug reproduction if every page has the version of the software on it.

git tags or githash ? Probably both so that it works at Dev and Production level.

**Comment by delaneyj** [comment]
I don't know what you mean, it's already there...

![image](https://github.com/delaneyj/datastar/assets/438252/6574f2e9-1d39-45a9-b000-d442f4c7637c)

![image](https://github.com/delaneyj/datastar/assets/438252/74586ee6-1503-43aa-b23e-81caa5fc827d)

**Comment by gedw99** [comment]
totally missed it. Was looking in the wrong area.

thanks @delaneyj
