### ISSUE TITLE
Todo: FOUC like behaviour on navigating back

### ISSUE THREAD

**Issue by gedw99** [delaneyj/datastar#90]
Tested on iOS Safari , but I presume it’s on all browsers.

v0.15.6

Reproduction:

1. Go to https://data-star.dev/
2. Scroll to bottom and select Let’s Get Staeted
3. Swipe back ( iOS or Android )

We get a jarring FOUC.

https://github.com/delaneyj/datastar/assets/53147028/b7856851-daf3-4d37-a65e-a6d991968508

**Comment by delaneyj** [comment]
Datastar is a server side rendered, the home specifically is using a compiled (from Tailwind/Daisy) css file.  It's not possible to have FOUC and this video doesn't show FOUC.  I can't tell but seems like a scroll issue possibly.

**Comment by gedw99** [comment]
Yeah it’s a scroll issue ..
